= spec-publish-asciidoc
:linkattrs:
Specification publishing using Asciidoc and UML

== Purpose
This repository contains a model publishing environment showing how technical specifications can be published in HTML, PDF and DocBook, based on authored content merged with UML models from a tool. The method will be used to replace openEHR.org's current method of publishing based on Adobe FrameMaker documents.

The type of technical specifications for which this approach is useful is standard-style documentation of formal artefacts, including:
* object models
* languages
* other formalisms.

== Description
The publishing environment takes two sources of input to create a logical specification:
* manually authored text (.adoc documents) and diagrams (any tool, as long as .png or .svg is generated)
* a formal UML model, represented in a UML tool.

We use http://asciidoctor.org/docs/what-is-asciidoc/[Asciidoc] as the source document syntax, the http://www.nomagic.com/[MagicDraw] UML tool for the models and http://asciidoctor.org[Asciidoctor] as the master publishing tool.

The general concept is that the overall specification is considered to be a manually authored artefact, which may include headings, complex formatting, tables, diagrams, source code, and any other features that would normally be expected in a sophisticated authoring toolset. Within this master document are 'include' statements for documents and diagrams generated from a formal model, such as a UML tool or programming environment.footnote:[There is an alternative theory that says specifications are completely represented inside a tool such as a UML tool, and it is responsible for generating the whole output. We don't believe this theory, mainly because UML tools are not good at dealing with arbitrary complex text, and also because UML isn't the only possible formalism that might be included in the output document. What is clearly needed is a standardised publishing environment that can deal with specifications about anything.]

Model elements are extracted from the UML tool and serialised as source documents and diagrams that are included in the master Asciidoc document using include statements.

The outputs are generated using asciidoctor tool.

== Status
Alpha

== Just Looking?
We have converted two large openEHR specifications to the new form - the AOM and the ADL specifications. You can see:

* AOM specification: source form link:docs/AOM2/[here]; https://rawgit.com/openEHR/spec-publish-asciidoc/master/docs/AOM2/AOM2.html[HTML view];
** features to look for: UML tool generated diagrams and specification tables;
* ADL specification: source form link:docs/ADL2/[here]; https://rawgit.com/openEHR/spec-publish-asciidoc/master/docs/ADL2/ADL2.html[HTML view];
** features to look for: machine highlighting using a newly developed ADL mode for Pygments;

The generated PDF is very rough and contains various errors that will be fixed with control over the PDF output stage.

== Workflow
The approach to building specification documentation and web resources is shown graphically https://rawgit.com/openEHR/spec-publish-asciidoc/master/workflow/workflow.html[here, window="_blank"].

To publish the specifications for one openEHR 'component' requires the Git repo of that component, e.g. https://github.com/openEHR/specifications-AM[specifiations-AM] and also this https://github.com/openEHR/spec-publish-asciidoc[spec-publish-asciidoc repository], which supplies the resource files (CSS, PDF theme, boilerplate text etc).

== Benefits
Once a toolchain like this is established, we can get the following benefits:

* model-based documentation is always up to date, as long as the models are maintained;
* specifications built like software, under continuous build on server;
* easier to report and fix errors, and to update documents, due to easy-ish source form;
* more flexibility to create new output formats.

== Installation

=== Publishing tools
To get the environment going you need quite a few tools. If you already have a working Ruby/gem environment, just skip to the Asciidoctor installation bit below.

WARNING: if you have never set up Ruby before, take some care. Experts suggest to install rvm first, and use that as a version manager. It's not strictly necessary, but may help what can otherwise become a versioning nightmare.

Rvm::
A ruby version manager. Install https://rvm.io/rvm/install[here].

Ruby::
See https://www.ruby-lang.org/en/documentation/installation/[install Ruby]. The scripts and commands in the publishing environment in this repository assume a unix-style environment, since the ultimate aim is to have it working under a Linux continuous build server. It can be set up on any normal machine; if you are on a Windows machine, using cygwin to run everything is probably advisable.
Rubygems::
On Linux see http://www.heatware.net/ruby-rails/how-to-install-rubygems-linux-ubuntu-10/[here]; Cygwin, use the https://cygwin.com/install.html[normal installer]. 
Asciidoctor::
The http://asciidoctor.org/[guidance on this page] pretty much covers it.
Pygments::
This supports code highlighting in the generated output. See http://asciidoctor.org/docs/user-manual/#pygments[here].
Asciidoctor-stylesheet-factory::
You don't need to install this unless you actually want to change the openehr.css or build new stylesheets. See https://github.com/asciidoctor/asciidoctor-stylesheet-factory[here].

=== MagicDraw and UML Extractor
If you have MagicDraw, you can install the UML extractor plugin in MagicDraw's plugin directory, under `org.openehr.docs.magicdraw`. The plugin files consist of one `.jar` and the `plugin.xml` file.  With this installed, start MagicDraw and open the project link:computable/UML/[openEHR_UML-AM.mdzip]. You will see an 'openEHR' menu option, with one option to extract documentation. Choose this, and choose `source/AOM2` as the output directory. The generated outputs will appear in the subdirectories `uml_diagrams` and `classes`.

=== Conversion of FrameMaker and other source documents
For conversion from Frame, the following approach is used:

* in Frame, for each chapter document, including 'Front.fm', but not TOC or end.fm, set HTML mappings for Heading types, List types and main Font types
* save each chapter as HTML
* hand-edit each file to fix `<pre></pre>` blocks, and heading level errors
* use pandoc to convert each HTML file xxxx.html to asciidoc, as follows

```
$ pandoc -f html -t asciidoc -o xxxx.adoc --no-wrap --atx-headers xxxx.html
```

=== Generating the publishing outputs
The following commands can be used to generate the HTML and PDF outputs:

[source,shell]
----------
$ ./publish.sh

$ ./publish.sh -p  # generate PDF as well - takes time

$ ./publish.sh -pt # generate PDF with tracing on, for debug purposes
----------

Have a look at this script to get an idea of how we are invoking asciidoctor.

=== Resources, styles and themes for HTML and PDF
We are using a stylesheet generated using the asciidoctor-stylesheet-factory; it is in `./resources/css/`. An early theme file for PDF, built according to the http://gist.asciidoctor.org/?github-asciidoctor%2Fasciidoctor-pdf%2F%2Fdocs%2Ftheming-guide.adoc[Asciidoctor-pdf theming guide] is in `./resources` as well.

== TODO
Many things...

* control PDF publishing properly
* sort out continuous build
